// This file was autogenerated by libs/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/bdoran/mvc/navigationviewcontroller.js', ['bdoran.mvc.NavigationViewController'], ['bdoran.mvc.ViewController', 'goog.array']);
goog.addDependency('../../../../src/bdoran/mvc/viewcontroller.js', ['bdoran.mvc.ViewController'], ['goog.ui.Component']);
goog.addDependency('../../../../src/bdoran/utils/soyviewcomponent.js', ['bdoran.utils.SoyViewComponent'], ['goog.ui.Component']);
goog.addDependency('../../../js_uncompiled/app/controller/frontviewcontroller.js', ['oc.app.controller.FrontViewController'], ['bdoran.mvc.NavigationViewController', 'bdoran.mvc.ViewController', 'goog.structs.Map', 'oc.app.controller.PageViewController', 'oc.app.view.components.MenuViewComponent']);
goog.addDependency('../../../js_uncompiled/app/controller/pageviewcontroller.js', ['oc.app.controller.PageViewController'], ['bdoran.mvc.ViewController', 'goog.ui.Container']);
goog.addDependency('../../../js_uncompiled/app/model/tweetmodel.js', ['oc.app.model.TweetModel'], ['goog.Uri.QueryData', 'goog.net.XhrIo', 'goog.structs.Map']);
goog.addDependency('../../../js_uncompiled/app/view/components/menuviewcomponent.js', ['oc.app.view.components.MenuViewComponent'], ['bdoran.utils.SoyViewComponent', 'goog.dom', 'goog.dom.classes', 'goog.events', 'goog.events.EventType', 'oc.app.view.templates.ViewComponentTemplates', 'soy']);
goog.addDependency('../../../js_uncompiled/app/view/templates/viewcomponenttemplates.js', ['oc.app.view.templates.ViewComponentTemplates'], ['soy', 'soy.StringBuilder']);
goog.addDependency('../../../js_uncompiled/init.js', ['oc.init'], ['oc.app.controller.FrontViewController']);
goog.addDependency('../../../libs/soy/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.string', 'goog.string.StringBuffer']);
